import bannerPng from '@/assets/main-banner-bg.png'
import bannerAvif960 from '@/assets/main-banner-bg-960.avif'
import bannerAvif1600 from '@/assets/main-banner-bg-1600.avif'
import bannerAvif1920 from '@/assets/main-banner-bg-1920.avif'
import bannerWebp960 from '@/assets/main-banner-bg-960.webp'
import bannerWebp1600 from '@/assets/main-banner-bg-1600.webp'
import bannerWebp1920 from '@/assets/main-banner-bg-1920.webp'
import { cn } from '@/lib/utils'

/**
 * The marketplace / auth banner, served responsively.
 *
 * The source PNG is a 1920x1080 photograph at 3.74 MB and was previously shipped as-is to
 * every marketplace and auth visitor. The same frame is 102 KB as AVIF. Variants are
 * generated by `scripts/optimise-static-assets.ts` and committed.
 *
 * The PNG stays as the final fallback so nothing regresses on a browser without WebP.
 */
export interface BannerImageProps {
  className?: string
  /** Above-the-fold heroes should pass 'eager'; decorative panels can lazy-load. */
  loading?: 'eager' | 'lazy'
  sizes?: string
}

/** Exported for use as a <video> poster, which cannot take a <picture>. */
export const bannerPosterSrc = bannerWebp1600

export function BannerImage({
  className,
  loading = 'eager',
  sizes = '100vw',
}: BannerImageProps) {
  return (
    <picture>
      <source
        type="image/avif"
        sizes={sizes}
        srcSet={`${bannerAvif960} 960w, ${bannerAvif1600} 1600w, ${bannerAvif1920} 1920w`}
      />
      <source
        type="image/webp"
        sizes={sizes}
        srcSet={`${bannerWebp960} 960w, ${bannerWebp1600} 1600w, ${bannerWebp1920} 1920w`}
      />
      <img
        src={bannerPng}
        alt=""
        loading={loading}
        decoding="async"
        className={cn('h-full w-full object-cover', className)}
      />
    </picture>
  )
}
